exports.LOGIN_TYPE = {
  FACEBOOK: 1,
  GOOGLE: 2,
  APPLE: 3,
  EMAIL_PASSWORD: 4,
  ISLOGIN: 5,
};

exports.VIDEO_TYPE = {
  NORMAL_VIDEO: 1,
  SHORT_VIDEO: 2,
};

exports.VISIBILITY_TYPE = {
  PUBLIC: 1,
  PRIVATE: 2,
  UNLISTED: 3,
};

exports.AUDIENCE_TYPE = {
  KIDS: 1,
  ADULTS: 2,
  BOTH: 3,
};

exports.COMMENT_TYPE = {
  ALLOW_ALL: 1,
  DISABLE: 2,
  HOLD_POTENTIALLY_INAPPROPRIATE_FOR_REVIEW: 3,
  HOLD_ALL_FOR_REVIEW: 4,
};

exports.SCHEDULE_TYPE = {
  SCHEDULED: 1,
  NOT_SCHEDULED: 2,
};

exports.PLAYLIST_TYPE = {
  PRIVATE: 1,
  PUBLIC: 2,
};

exports.REPORT_TYPE = {
  SEXUAL: 1,
  VIOLENT_OR_REPULSIVE: 2,
  HATEFUL_OR_ABUSIVE: 3,
  HARMFUL_OR_DANGEROUS: 4,
  SPAM_OR_MISLEADING: 5,
  CHILD_ABUSE: 6,
  OTHERS: 7,
};

exports.WITHDRAWAL_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINE: 3,
};

exports.MONETIZATIONREQUEST_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINE: 3,
};
